Correct string generator for finite automata
FormalLanguageConstrainedPathQuerying/pyformlang pull request #11
Opened 2024-10-16 11:44 UTC by bygu4

https://github.com/FormalLanguageConstrainedPathQuerying/pyformlang/pull/3

2024-10-16 21:36 UTC, bygu4 commented
I don't see a good way of avoiding word duplicates, we also can't use Set for it

2024-10-18 09:29 UTC, WoWaster reviewed
See Telegram about duplication

2024-10-18 09:29 UTC, WoWaster commented on pyformlang/finite_automaton/finite_automaton.py
> +        states_to_visit = [(start_state, [])
Can we use https://docs.python.org/3/library/collections.html#collections.deque here?

2024-10-18 09:29 UTC, WoWaster commented on pyformlang/finite_automaton/finite_automaton.py
> +        states_to_process = [(None, start_state)
And here?

2024-10-21 05:59 UTC, gsvgit requested changes

2024-10-21 05:59 UTC, gsvgit commented on pyformlang/finite_automaton/finite_automaton.py
> +            if len(current_word) > max_length and max_length != -1:
What if I pass -13 as `max_length`?

2024-10-21 05:59 UTC, gsvgit commented on pyformlang/finite_automaton/finite_automaton.py
> +    def _get_states_leading_to_final(self) -> Set[State]:
What about generalization of [this](https://github.com/Aunsiels/pyformlang/blob/4f36e28492a529d67129dcecaf9d07ca69fb0cf6/pyformlang/finite_automaton/deterministic_finite_automaton.py#L303) function? And what about generalization using NetworkX?

2024-10-21 05:59 UTC, gsvgit commented on pyformlang/finite_automaton/finite_automaton.py
> +            current_state, current_word = states_to_visit.popleft()
Looks like you should add `visited_states` to prevent trivial duplicates.

2024-10-21 05:59 UTC, gsvgit commented on pyformlang/finite_automaton/tests/test_epsilon_nfa.py
> +def get_cyclic_enfa_example():
Add test with epsilon-cycle.

2024-10-21 10:16 UTC, gsvgit commented on pyformlang/finite_automaton/finite_automaton.py
> +        if max_length and max_length < 0:
Add more tests on `max_length=0`: epsilon chains, start state equals to the final one, language that does not contain empty string.

2024-10-21 13:41 UTC, bygu4 commented on pyformlang/finite_automaton/finite_automaton.py
> +            current_state, current_word = states_to_visit.popleft()
I don't see how it would help us prevent duplicates: state can be reached multiple times but produce different words. Maybe we could store words generated by each state, but I think we can try looking for epsilon cycles specifically

2024-10-26 06:07 UTC, gsvgit commented on pyformlang/finite_automaton/epsilon_nfa.py
> +    def accepts(self, word: Iterable[Any]) -> bool:
Strange constraints relaxation.

2024-10-26 06:09 UTC, gsvgit commented on pyformlang/cfg/cfg.py
> +                 variables: AbstractSet[Union[Variable, str]] = None,
Why terminals and variables are union? Looks like design issue.

2024-10-26 08:53 UTC, gsvgit approved these changes

2024-10-26 08:58 UTC, merged